apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $APP_NAME
  name: $APP_NAME
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      imagePullSecrets:
        - name: harbor-auth
      containers:
        - env:
            - name: CHAIN_ID
              value: '2810'
            - name: RPC_URL
              value: https://rpc-holesky.morphl2.io
            - name: API_URL
              value: http://dex-backend.dev-dex.svc:3000/v1
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$VERSION
          livenessProbe:
            httpGet:
              path: /v1/health
              port: 3000
              scheme: HTTP
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /v1/health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 2
            timeoutSeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: Always
          name: $APP_NAME
          ports:
            - name: http-3000
              containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 200Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always