apiVersion: v1
kind: Service
metadata:
  labels:
    app: $APP_NAME
  name: $APP_NAME
spec:
  ports:
    - name: tcp-3000
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: $APP_NAME
  sessionAffinity: None
  clusterIP: None
  type: ClusterIP